export const storeProducts = [
  {
    id: 1,
    title: "Women's Pointed-Toe Ballet Flat",
    img: "https://m.media-amazon.com/images/I/61WizR5wiLL._AC_UL320_.jpg",
    price: 27.4,
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Men's Lite Racer Adapt 3.0 Running Shoe",
    img: "https://m.media-amazon.com/images/I/71StEHAlKIL._AC_UL320_.jpg",
    price: 53,
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Sperry Men's Authentic Original 2-Eye Boat Shoe",
    img: "https://m.media-amazon.com/images/I/81TYMRzGmxL._AC_UL320_.jpg",
    price: 94,
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Clarks Men's Tilden Cap Oxford Shoe",
    img: "https://m.media-amazon.com/images/I/81n+HernnfL._AC_UL320_.jpg",
    price: 44,
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Steve Madden Men's Fenta Fashion Sneaker",
    img: "https://m.media-amazon.com/images/I/813UuOjWfZL._AC_UL320_.jpg",
    price: 59,
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Under Armour Men's Charged Assert 9 Running Shoe",
    img: "https://m.media-amazon.com/images/I/71dzaYg56AS._AC_UL320_.jpg",
    price: 60,
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Under Armour Men's Lockdown 5 Basketball Shoe",
    img: "https://m.media-amazon.com/images/I/71lJ6LMJfUL._AC_UL320_.jpg",
    price: 64,
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "adidas Men's Questar Flow Nxt Running Shoe",
    img: "https://m.media-amazon.com/images/I/71n1I0GBs3L._AC_UL320_.jpg",
    price: 60,
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title:
      "FLYFUPPY Womens Shoes Slip-on Fashion Sneakers Round Toe Comfort Walking Shoes",
    img: "https://m.media-amazon.com/images/I/71Mt2OZWjLS._AC_UL320_.jpg",
    price: 27,
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Merrell Men's Moab 2 Vent Hiking Shoe",
    img: "https://m.media-amazon.com/images/I/81m9GyEmoRL._AC_UL320_.jpg",
    price: 83,
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Women's Pointed-Toe Ballet Flat",
  img: "https://m.media-amazon.com/images/I/61WizR5wiLL._AC_UL320_.jpg",
  price: 27.4,
  info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  inCart: false,
  count: 0,
  total: 0,
};
